### ISSUE TITLE
not working for woff, ttf files

### ISSUE THREAD

**Issue by ninjasort** [DustinJackson/html-webpack-inline-source-plugin#10]
Does this work for woff, ttf files? I have the following settings:

```js
inject: false,
inlineSource: '.(woff|ttf)$',
template: './src/index.html'
```

I get errors from some these files when I load the bundle on a subroute

**Comment by d-bitz** [comment]
No this plugin modifies the _injected_ css or javascript generated by the html-webpack-plugin.

**Comment by brhx** [comment]
Oh wow I'm a plonker, took me a while to realise this. Is there some documentation I was silly enough to skip over?
