### ISSUE TITLE
Sourcemap TypeError: code.match is not a function

### ISSUE THREAD

**Issue by stevewillard** [DustinJackson/html-webpack-inline-source-plugin#13]
Anyone getting this error?
```
- source-map-url.js:35 Object.getFrom
    [my-project]/[source-map-url]/source-map-url.js:35:24
  
  - index.js:57 HtmlWebpackInlineSourcePlugin.resolveSourceMaps
    [my-project]/[html-webpack-inline-source-plugin]/index.js:57:37
  
  - index.js:112 HtmlWebpackInlineSourcePlugin.processTag
    [my-project]/[html-webpack-inline-source-plugin]/index.js:112:30
  
  - index.js:45 
    [my-project]/[html-webpack-inline-source-plugin]/index.js:45:20
  
  - Array.forEach
  
  - index.js:44 HtmlWebpackInlineSourcePlugin.processTags
    [my-project]/[html-webpack-inline-source-plugin]/index.js:44:19
```

I'm using devtool: 'cheap-module-source-map'

and my Plugin config looks like this:
```
  new HtmlWebpackPlugin({
    template: 'src/app/index.html',
    inject: 'body',
    favicon: 'src/app/favicon.png',
    inlineSource: ENV_PROD ? '(vendor)|(my\.app)' : ''
  }),
```

It looks like it's coming from:
```
// Extract original sourcemap URL from source string
var mapUrlOriginal = sourceMapUrl.getFrom(source);
```

**Comment by d-bitz** [comment]
@AndyBarron any ideas ? :)

**Comment by andybarron** [comment]
Huh, is it originating inside `source-map-url`? I'll see if I can repro...

**Comment by d-bitz** [comment]
yeah looks like it, just wondering if you'd seen this before

**Comment by andybarron** [comment]
Nope. I wonder if `source-map-url` expects a string and we're passing a Buffer or something like that.

**Comment by stevewillard** [comment]
Yup, you're right. It looks like a Buffer. Added a console.log in that function in `source-map-url`

```
code is... <Buffer 1f 8b 08 00 00 00 00 00 02 03 ec bd f9 77 db 48 92 20 fc fb fe 15 12 a6 56 0d 14 21 8a f7 01 1a c5 75 c9 f2 94 77 7c 68 6d b9 8f 95 58 6a 10 48 92 68 ... >
```

Also for some reason it only happens when I set NODE_ENV=production

Edit: I narrowed it down a bit more. It seems to only be an issue when I enable `compression-webpack-plugin` - Maybe I'll just use some other mechanism for gzipping.

**Comment by d-bitz** [comment]
any updates on this @stevewillard?

**Comment by stevewillard** [comment]
I kind of gave up for now. I think I'll probably switch to compressing my assets without the compression plugin.
