### ISSUE TITLE
What is this plugin supposed to do?

### ISSUE THREAD

**Issue by netpoetica** [DustinJackson/html-webpack-inline-source-plugin#2]
I am under the impression that this is what you expect:

```
myProject/
- src/
- - utils.js
- - static/
- - - - index.html
- webpack.config.js
```

src/index.html
```
<html>
  <script src='./utils.js'></script>
  <body>
  </body>
</html>
```

src/utils.js
```
function doStuff() {
  console.log('doing so much stuff.');
}
```

webpack.config.js
```
...
    new HtmlWebpackPlugin({
      template: path.join(STATIC_ASSETS_DIR, 'index.html'),
      hash: false,
      // Don't inject main.js, etc
      inject: false,
      inlineSource: '.(js)$',
      filename: 'index.html',
      minify: {
        collapseWhitespace: true
      }
    }),
    new HtmlWebpackInlineSourcePlugin()
...
```

And then when you run webpack, you expect

dist/index.html
```
<html>
  <script>
    function doStuff() {
      console.log('doing so much stuff.');
    }
  </script>
  <body>
  </body>
</html>
```

Is this not what this plugin is supposed to do?

**Comment by d-bitz** [comment]
It only embeds source for the injected assets, you have `inject: false` in your config.

**Comment by netpoetica** [comment]
But if I use inject: true, it's gonna inject the "entry"...

```
  entry: [
    path.join(SRC_DIR, 'main.js')
  ],
```

What if you just want to inject some specific JS asset into some specific static HTML asset?

Picture:

```
myProject/
- src/
- - utils.js
- - main.js (require's utils.js in node environment, is application entry point)
- - static/
- - - - index.html (requires utils.js in browser environment)
- webpack.config.js
```

And you have a main index.html for your application which uses main.js as entry point, but static/index.html will also want to inject utils.js.

**Comment by d-bitz** [comment]
Maybe you could leverage multiple entry points and the [commonschunkplugin](https://webpack.github.io/docs/list-of-plugins.html#commonschunkplugin).  

As I mentioned this plugin only processes assets that are injected into the html document.  It does this by hooking into html-webpack-plugin's event for generating the tag definitions.  If your use case extends beyond this functionality it might not be the right fit.  I have used [inline source](https://github.com/popeindustries/inline-source) in the past which I found quite helpful.

**Comment by netpoetica** [comment]
All right, thank you! I will try to use these tools. Thanks for clarifying!
