### ISSUE TITLE
causing error if script file is in relative path

### ISSUE THREAD

**Issue by jose3ww** [DustinJackson/html-webpack-inline-source-plugin#21]
webpack run causes the error.
webpack version is  2.3.2.

Error message:

ERROR in   TypeError: Cannot read property 'source' of undefined

  - index.js:52 HtmlWebpackInlineSourcePlugin.resolveSourceMaps
    [xxxxxx]/[html-webpack-inline-source-plugin]/index.js:52:21

related part of webpack.config.js

 plugins: [
    new HtmlWebpackPlugin({
      template: 'src/static/index.html',
      inject: 'true',
      filename: 'index.html',
      inlineSource: '.(js|css)$', // embed all javascript and css inline
    }),
    new HtmlWebpackInlineSourcePlugin(),
 ]

quick fix is to modify the end of processTag() as:

if (assetUrl) {
    // Strip query string (e.g. cache busting hash) from asset URL
    assetUrl = assetUrl.replace(/\?.*$/, '');
    // Strip public URL prefix from asset URL to get Webpack asset name
    var assetName =
      (compilation.outputOptions.publicPath) ?
      path.posix.relative(publicUrlPrefix, assetUrl) :
      assetUrl;
    var asset = compilation.assets[assetName];
    var updatedSource = this.resolveSourceMaps(compilation, assetName, asset);
    tag.innerHTML = updatedSource;
  }

This is just a quick fix and I'm not sure this is appropriate.

**Comment by ifdouglas-zz** [comment]
What do you mean with "the end of processTag()". Where exactly?

**Comment by jose3ww** [comment]
here's the diff of index.js

hope this helps, although this is not a good solution.


2018-04-05 23:49 GMT+09:00 Douglas Fernandes <notifications@github.com>:
