### ISSUE TITLE
inlined script should be escaped

### ISSUE THREAD

**Issue by jose3ww** [DustinJackson/html-webpack-inline-source-plugin#22]
the inlined script including string "</script>"  should be escaped.

quick fix is, at the end of processTag(), 

    tag.innerHTML = (tag.tagName === 'script') ? updatedSource.replace(/<\/script>/g, '<\\/script>') : updatedSource;

I'm not expert of Javascript/HTML, and not sure it's appropriate changes.

**Comment by d-bitz** [comment]
added https://github.com/DustinJackson/html-webpack-inline-source-plugin/commit/bdc4e564d37887aba2785c544845b675b2961ac7
