### ISSUE TITLE
Javascript file still in dist folder

### ISSUE THREAD

**Issue by JordyMoos** [DustinJackson/html-webpack-inline-source-plugin#27]
I added your sample from the readme to my webpack config file. And the javascript is now inlined in my html (as requested)

But the javascript file also still is in my dist folder (which is no longer needed) is there a flag or so that the used javascript file is removed?

Thanks

**Comment by d-bitz** [comment]
PR's welcome

**Comment by drifterz28** [comment]
I just added webpack-clean to my config and removed the files. that seems to work just fine.

I hope that helps. I would try and PR this but I am not wise enough :)

**Comment by doguh** [comment]
```js
const { CleanWebpackPlugin } = require("clean-webpack-plugin");

const config = {
  ...
  plugins: [
    new HtmlWebpackPlugin({
      inlineSource: ".(js|css)$", // embed all javascript and css inline
      inject: true,
      template: "./public/index.html"
    }),
    new HtmlWebpackInlineSourcePlugin(),
    new CleanWebpackPlugin({
      protectWebpackAssets: false,
      cleanAfterEveryBuildPatterns: ["*.js"]
    })
  ],
  ...
};
```
