### ISSUE TITLE
Delete the inlined files

### ISSUE THREAD

**Issue by Hubro** [DustinJackson/html-webpack-inline-source-plugin#29]
When I've inlined a file into my HTML document, I no longer need that file in the dist folder. It would be nice if this plugin included an option to automatically delete that file from the dist folder.

**Comment by Hubro** [comment]
If anybody else has the same issue, I wrote a quick and dirty solution, but it would be simpler if `html-webpack-inline-source-plugin` could delete the files for me.

```javascript
const path = require('path');
const fs = require('fs');

function DeleteChunksPlugin(config) {
    this.config = config;
    this.deleteFiles = [];

    if (this.config.chunks === undefined) this.config.chunks = [];
}

DeleteChunksPlugin.prototype.apply = function(compiler) {
    const self = this;

    compiler.plugin('emit', function(compilation, callback) {
        compilation.chunks.forEach(function(chunk) {
            if (self.config.chunks.indexOf(chunk.name) > -1) {
                chunk.files.forEach(function(file) {
                    self.deleteFiles.push(path.resolve('dist', file));
                });
            }
        });

        callback();
    });

    compiler.plugin('done', function() {
        self.deleteFiles.forEach(function(file) {
            console.log("Deleting inlined file", file);
            fs.unlink(file);
        });
    });
};

module.exports = DeleteChunksPlugin;
```

Usage:

```javascript
new DeleteChunksPlugin({
    // These chunks have been inlined into the HTML and can be deleted
    chunks: ['manifest', 'polyfills']
})
```

**Comment by tzookb** [comment]
I simply used this "delete" plugin:
https://www.npmjs.com/package/webpack-clean

quite easy

**Comment by brunocodutra** [comment]
Better yet, you may use [`ignore-assets-webpack-plugin` ](https://github.com/medfreeman/ignore-assets-webpack-plugin/) to avoid assets from being emitted in the first place.

Besides preventing unnecessary writes to disk, this approach has the additional advantage of removing dropped assets from the summary printed by webpack after compilation.

<del>
**NOTE:** until medfreeman/ignore-assets-webpack-plugin#1 is merged you can use:

```
"ignore-assets-webpack-plugin": "git://github.com/brunocodutra/ignore-assets-webpack-plugin.git#dist",
```
</del>

**Comment by medfreeman** [comment]
fyi it has been merged and released as 2.0.1

**Comment by D1g1talEntr0py** [comment]
[ignore-assets-webpack-plugin](https://github.com/medfreeman/ignore-assets-webpack-plugin/) works fine _IF_ you know the exact name of the file you want to ignore. But what about when using the [name] & [chunkhash] placeholders?

Here I extract the CSS into a separate file when doing a production build. How can I ignore this using the [ignore-assets-webpack-plugin](https://github.com/medfreeman/ignore-assets-webpack-plugin/)
`new ExtractTextPlugin({ filename: 'assets/styles/[name].[chunkhash].css', allChunks: true, disable: !env.prod })`

**Comment by PezzerDev** [comment]
@Naquaduh I was stuck in a similar situation and was able to filter out the files I don't want emitted with [filter-chunk-webpack-plugin](https://github.com/yeojz/filter-chunk-webpack-plugin). It allows for glob patterns.

That said, I'd much prefer an option in `html-webpack-inline-source-plugin` to simply filter out files that have been inlined.

**Comment by D1g1talEntr0py** [comment]
@SpenceDiNicolantonio Awesome. Thank you for the info. I'll have to give that a try.

**Comment by andreasvirkus** [comment]
@SpenceDiNicolantonio  @DustinJackson Is there a way to also remove the `script` or `link` tag from being added to the final html file?

**Comment by corentinaltepe** [comment]
@DustinJackson : Why was this ticket closed? Is there an option now in the plugin to filter out the inlines resources?

**Comment by alsrbbk** [comment]
@corentinaltepe [CleanWebpackPlugin](https://github.com/johnagan/clean-webpack-plugin) with the following options can be a solution for me.
```javascript
{
    plugins: [
        new HtmlWebPackPlugin({
            inlineSource: /\.(js|css)$/
        }),
        new CleanWebpackPlugin({
            protectWebpackAssets: false,
            cleanAfterEveryBuildPatterns: ["**/*.js", "**/*.css"]
        }),
        new HtmlWebPackInlineSourcePlugin()
    ]
}
```
