### ISSUE TITLE
ParseError

### ISSUE THREAD

**Issue by madshargreave** [DustinJackson/html-webpack-inline-source-plugin#3]
I get the following error when I try to run the plugin

```
Error: Parse Error: <\?xml/,end:/\?>/,relevance:10},{begin:/<\?\w+/,end:/\?>/}]},{className:"tag",begin:"</?",end:"/?>",contains:[{className:"name",begin:/[^\/><\s]+/,relevance:0},n]}]}}}
```

My config:

```
 new HtmlWebpackPlugin({
    template: paths.client('landing.html'),
    inlineSource: '.(js|css)$',
    hash: false,
    filename: `landing.[${config.compiler_hash_type}].html`,
    chunks: ['landing'],
    injectSrc: true,
    inject: 'body',
    minify: {
      collapseWhitespace: true
    }
  }),
  new HtmlWebpackInlineSourcePlugin(),
```

**Comment by d-bitz** [comment]
From what you posted I can't tell where parse error is coming from.  

This plugin is pretty basic, all it does is modify the tag definitions generated by the html-webpack-plugin to set the `innerHTML` property of the tag.  If you aren't [escaping](http://stackoverflow.com/questions/8231048/why-use-x3c-instead-of-when-generating-html-from-javascript) your source then perhaps this could cause parsing problems.

This plugin could be extended to escape the source automatically...  PR's are welcome!

**Comment by d-bitz** [comment]
I'm going to close this for now, let me know if you investigate this further or have any other questions.

**Comment by madshargreave** [comment]
Do you know if there is a way to automatically escape the source using webpack?

**Comment by d-bitz** [comment]
I'm not sure.  Maybe you could use the [string replace loader](https://www.npmjs.com/package/string-replace-loader#regex-replacement).  I have used this [inline source](https://github.com/popeindustries/inline-source) plugin in the past and it escapes javascript using the following [regex](https://github.com/popeindustries/inline-source/blob/master/lib/js.js#L5).

Maybe it would be a good idea to add an "escape source" option to this plugin.
