### ISSUE TITLE
regex syntax?

### ISSUE THREAD

**Issue by ericat** [DustinJackson/html-webpack-inline-source-plugin#36]
Not sure what the regex to match a specific file is supposed to be.

My config is essentially:

```
  context: __dirname,
  entry: [
    './public/js/app.js',
    './public/js/form.js',
    'webpack-dev-server/client',
  ],
  devServer: {
    contentBase: './public',
    watchContentBase: true,
    port: 3006,
  },
  output: {
    path: path.resolve(__dirname, 'public'),
    publicPath: '/',
    filename: 'bundle.js',
  },

...
    new HtmlWebpackPlugin({
      template: path.resolve(__dirname, 'public/index.html'),
      // inject: true,
      inlineSource: 'form.js'
    }),
    new HtmlWebpackInlineSourcePlugin()
...
```

I don't want to embed everything, so this won't work: '.(js|css)$'

But nothing seems to be capturing just the "form" (tried several patterns). What am I doing wrong?

**Comment by usulpro** [comment]
Hey @ericat this plugin can't inline separate js file, only separate chunk. And the `regexp` should match that chunk name. So in your case, for example, you first need to create separate entry point for your file and specify its name:

```js
entry: [
    './public/js/app.js',
    'form-inline': './public/js/form.js',
    'webpack-dev-server/client',
  ],
```
then note that generated chunk name could looks like `form-inline.345345345.js` so you can setup plugin this way:

```js
new HtmlWebpackPlugin({
      template: path.resolve(__dirname, 'public/index.html'),
      // inject: true,
      inlineSource: /form-inline\.\d*\.js$/
    }),
```
