### ISSUE TITLE
Help maintain this plugin!

### ISSUE THREAD

**Issue by d-bitz** [DustinJackson/html-webpack-inline-source-plugin#40]
If anyone would like to help maintain this plugin please send me a message

**Comment by iamakulov** [comment]
I’d suggest to move this package into [the webpack-contrib community](https://github.com/webpack-contrib). This would allow the community to maintain it and update as necessary (e.g., upgrade for next versions of webpack).

It’s not as good as a single maintainer responsible for the whole project, but it’s a viable alternative, in my opinion.
