### ISSUE TITLE
Does this plugin play well with split JS bundles

### ISSUE THREAD

**Issue by harrysolovay** [DustinJackson/html-webpack-inline-source-plugin#48]
Hi,

I was wondering whether this plugin accounts for code-splitting? I'm using [react-loadable](https://github.com/jamiebuilds/react-loadable), but would love to inline the main bundle to speed up the first request. Please let me know. Thank you!

Kind regards,

Harry

**Comment by harrysolovay** [comment]
@DustinJackson common man... closed with no response? Even an "I don't know" would be 💯

**Comment by d-bitz** [comment]
It’s been 6 months... did you not try it out?

**Comment by harrysolovay** [comment]
No––I'm sorry for trolling. Thank you anyways 👍
