### ISSUE TITLE
Inline css twice in Vue-CLI 3 with html-webpack-inline-source-plugin

### ISSUE THREAD

**Issue by logan70** [DustinJackson/html-webpack-inline-source-plugin#50]
## Expected behavior

Size of my css file is 13.8kb, html is 2.8kb. So I wanna that my css file can be inlined with html-webpack-inline-source-plugin.

## Current behavior

The size of my html file increased to 30.4kb
And I found that my css file was inlined twice.

## Config

Adding this plugin by webpack-chain API
```js
// vue.config.js
const HtmlWebpackInlineSourcePlugin = require('html-webpack-inline-source-plugin')
module.exports = {
    chainWebpack: config => {
        config.plugin('html').tap(args => {
            args[0].inlineSource = '.css$'
            return args
        }
        config.plugin('inline').use(HtmlWebpackInlineSourcePlugin)
    }
}
```

When I inspecting my project's webpack config
_vue inspect > output.js_

```js
// output.js
/* config.plugin('html') */
new HtmlWebpackPlugin(
  {
    templateParameters: function () { /* omitted long function */ },
    template: '/Users/logan/tencent/qgact/src/index.html',
    filename: 'index.html',
    inlineSource: '.css$'
  }
),
/* config.plugin('inline') */
new HtmlWebpackInlineSourcePlugin()
```

## Enviroment

```
Node.js 10.9.0
@vue/cli-service 3.0.0
webpack 4.15.1
html-webpack-plugin 3.2.0
html-webpack-inline-source-plugin 0.0.10
```

**Comment by logan70** [comment]
It works when I use `html-inline-css-webpack-plugin`

```js
// vue.config.js
const HtmlWebpackInlineSourcePlugin = require('html-webpack-inline-source-plugin')
module.exports = {
    chainWebpack: config => {
        config.plugin('inline').use(require('html-inline-css-webpack-plugin').default)
    }
}

**Comment by mcallan83** [comment]
I am experiencing the same issue. Using vue-cli and this plugin, both my JS and CSS are being inlined twice.

**Comment by logan70** [comment]
> I am experiencing the same issue. Using vue-cli and this plugin, both my JS and CSS are being inlined twice.
Cuzz Vue-cli 3 will auto add preload link tag to your html like this.
` <link href=js/app.js rel=preload as=script>`

**Comment by logan70** [comment]
> I am experiencing the same issue. Using vue-cli and this plugin, both my JS and CSS are being inlined twice.

Vue-cli 3 would use @vue/preload-webpack-plugin to auto add preload link tag to your html like this

` <link href=js/app.js rel=preload as=script>`

`<link href=css/app.css rel=preload as=style>`,

you can modify this plugin's config in vue.config.js(if you don't have this file, create it in your project's root folder)

```js
module.exports = {
  chainWebpack: config => {
    config.plugin('preload')
      .tap(args => {
        args[0].fileBlacklist.push(/\.css/, /app\.js/)
        return args
      })
    config.plugin('inline-source')
      .use(require('html-webpack-inline-source-plugin'))
    config
      .plugin('html')
      .tap(args => {
        args[0].inlineSource = '(\.css|app\.js$)'
        return args
      })
  }
}
```
If it works, let me know.

**Comment by mcallan83** [comment]
@logan70, this did the trick! It looks like this was more of a config issue if anything. Thanks for your help.

**Comment by danon** [comment]
> > I am experiencing the same issue. Using vue-cli and this plugin, both my JS and CSS are being inlined twice.
> 
> Vue-cli 3 would use @vue/preload-webpack-plugin to auto add preload link tag to your html like this
> 
> ` <link href=js/app.js rel=preload as=script>`
> 
> `<link href=css/app.css rel=preload as=style>`,
> 
> you can modify this plugin's config in vue.config.js(if you don't have this file, create it in your project's root folder)
> 
> ```js
> module.exports = {
>   chainWebpack: config => {
>     config.plugin('preload')
>       .tap(args => {
>         args[0].fileBlacklist.push(/\.css/, /app\.js/)
>         return args
>       })
>     config.plugin('inline-source')
>       .use(require('html-webpack-inline-source-plugin'))
>     config
>       .plugin('html')
>       .tap(args => {
>         args[0].inlineSource = '(\.css|app\.js$)'
>         return args
>       })
>   }
> }
> ```
> 
> If it works, let me know.

This doesn't work for me, it still renders everything in folder `dist` :/

**Comment by imaxing** [comment]
> 

how you have since resolved this issue? :)
