### ISSUE TITLE
How to inline .css from a <link> tag?

### ISSUE THREAD

**Issue by itsnotatbug** [DustinJackson/html-webpack-inline-source-plugin#53]
First of all, great plugin. Appreciate the work put into it.

I am trying to inline the .css source that comes from my `<link>` tag in the template file into the quoted.html file. Is this possible? If not, how do you inline CSS into the finalized file?

Inside plugins:
		`new HtmlWebpackPlugin({`
			`  inlineSource: '.(js|css)$',`
			`  filename: 'quoted.html',`
			`  template: 'src/quoted/quotedTemplate.html'`
		`})`
`new HtmlWebpackInlineSourcePlugin()`

**Comment by AntonioRedondo** [comment]
I also wonder the same. I feel the documentation is a bit lacking. A small example would help on `README.md`.

**Comment by Timur00Kh** [comment]
Same question
