### ISSUE TITLE
AssertionError [ERR_ASSERTION]: The HtmlWebpackInlineSourcePlugin does not accept any options

### ISSUE THREAD

**Issue by TheKnarf** [DustinJackson/html-webpack-inline-source-plugin#56]

**Comment by hsxfjames** [comment]
seems only the beta version accepts options like which was documented at README.md

**Comment by maxHoo** [comment]
same issue, tried with web pack 3.26 and 4.26.

**Comment by henbenla** [comment]
same issue.

solved the problem by using:
* html-webpack-plugin@4.0.0-beta.4
* html-webpack-inline-source-plugin@1.0.0-beta.2

**Comment by coreykress** [comment]
I was also dealing with this, but I got around it by removing HtmlWebpackPlugin from the constructor in the webpack config.

i.e.
`new HtmlWebpackInlineSourcePlugin()`
