### ISSUE TITLE
Cannot read property 'tapAsync' of undefined

### ISSUE THREAD

**Issue by shaded-enmity** [DustinJackson/html-webpack-inline-source-plugin#63]
Using `index.js` from https://github.com/DustinJackson/html-webpack-inline-source-plugin/pull/55/files works just fine.

**Comment by mark-spurgeon** [comment]
same here, but the index.js @shaded-enmity shows also throws an error for me

**Comment by shaded-enmity** [comment]
@the-duck Did you also tweak your webpack config? So that you include it as:
```js
plugins: [
    new HtmlWebpackInlineSourcePlugin(HtmlWebpackPlugin)
]
```

**Comment by metronom72** [comment]
For me it throw ```AssertionError [ERR_ASSERTION]: The HtmlWebpackInlineSourcePlugin does not accept any options```

**Comment by Sangdt** [comment]
> @the-duck Did you also tweak your webpack config? So that you include it as:
> 
> ```js
> plugins: [
>     new HtmlWebpackInlineSourcePlugin(HtmlWebpackPlugin)
> ]
> ```

`
function HtmlWebpackInlineSourcePlugin (htmlWebpackPlugin) {
  this.htmlWebpackPlugin = htmlWebpackPlugin;
}
HtmlWebpackInlineSourcePlugin.prototype.apply = function (compiler) {
  var self = this;

  // Hook into the html-webpack-plugin processing

   compiler.hooks.compilation.tap('html-webpack-inline-source-plugin', compilation => {
    self.htmlWebpackPlugin
      .getHooks(compilation)
      .alterAssetTagGroups.tapAsync('html-webpack-inline-source-plugin', (htmlPluginData, callback) => {
        if (!htmlPluginData.plugin.options.inlineSource) {
          return callback(null, htmlPluginData);
        }

        var regexStr = htmlPluginData.plugin.options.inlineSource;

        var result = self.processTags(compilation, regexStr, htmlPluginData);

        callback(null, result);
      });
    });
};

HtmlWebpackInlineSourcePlugin.prototype.processTags = function (compilation, regexStr, pluginData) {
  var self = this;

  var bodyTags = [];
  var headTags = [];

  var regex = new RegExp(regexStr);

  pluginData.headTags.forEach(function (tag) {
    headTags.push(self.processTag(compilation, regex, tag));
  });

  pluginData.bodyTags.forEach(function (tag) {
    bodyTags.push(self.processTag(compilation, regex, tag));
  });

  return { headTags: headTags, bodyTags: bodyTags, plugin: pluginData.plugin, chunks: pluginData.chunks, outputName: pluginData.outputName };
};
.....
`
I fix it like this with the index.js from https://github.com/DustinJackson/html-webpack-inline-source-plugin/pull/55/files 
It work for me.

**Comment by paambaati** [comment]
I'm facing the same error; does anyone have a fully working solution?

**Comment by phil294** [comment]
@paambaati as Sangdt said, it's fixed in the linked pull request. To use it, you have to specify the 1.0.0-beta.2 version in your package.json as of now, and pass the `HtmlWebpackPlugin` like `new HtmlWebpackInlineSourcePlugin(HtmlWebpackPlugin)`. With this setup, it works fine.

**Comment by AntonioRedondo** [comment]
Is the fix gonna be ever published on the final production stream? It still hasn't moved from beta state.

**Comment by lautarodragan** [comment]
@AntonioRedondo see https://github.com/DustinJackson/html-webpack-inline-source-plugin/issues/76#issuecomment-617539736
