### ISSUE TITLE
Inline font assets 

### ISSUE THREAD

**Issue by kilgarenone** [DustinJackson/html-webpack-inline-source-plugin#65]
I have a custom `index.html` like this:

```
<!DOCTYPE html>
<html lang="en">
  <head>
     <style>
        @font-face {
          font-family: Inter;
          src: url("<%= ?????? %>") format("woff2");
        }
     </style>
```
I would like to get the font asset file that might look like `inter.hash123.woff` and place it in the inline style CSS.

**Comment by d-bitz** [comment]
parsing script contents is beyond the scope of this plugin
