### ISSUE TITLE
The plugin processes the preload node

### ISSUE THREAD

**Issue by HydrogenPan19** [DustinJackson/html-webpack-inline-source-plugin#66]
Plugin processing preload node

Does the plugin need to skip the preload , prefetch node?

**Comment by d-bitz** [comment]
can you elaborate? example? 

closing, old issue

**Comment by HydrogenPan19** [comment]
Well, it's been a long time.
It seems that the plugin will read the preload node and inline its code on the html.
In general, we just want to inline ordinary js. 
It's not really important, I'm just asking if the plugin need to skip the preload node.
