### ISSUE TITLE
Not working with webpack 4

### ISSUE THREAD

**Issue by throne1986** [DustinJackson/html-webpack-inline-source-plugin#74]
I followed all instructions provided online but in my webpack confgi file I have this

`[Could not find a declaration file for module 'html-webpack-inline-source-plugin'. 'c:/custom-xammp/htdocs/videomill-dashboard/node_modules/html-webpack-inline-source-plugin/index.js' implicitly has an 'any' type.
  Try `npm install @types/html-webpack-inline-source-plugin` if it exists or add a new declaration (.d.ts) file containing `declare module 'html-webpack-inline-source-plugin';`ts(7016)](url)`

> What do I need to do to solve this problem?

**Comment by ChristianRich** [comment]
I concur. Unable to get this working with WebPack4.

```
TypeError: Cannot read property 'tapAsync' of undefined
    at /Users/work/Documents/projects/login-form/node_modules/html-webpack-inline-source-plugin/index.js:21:59
```

**Comment by d-bitz** [comment]
duplicate, closing
