### ISSUE TITLE
Not working with new html-webpack-plugin@version 4.0.1 (near)

### ISSUE THREAD

**Issue by DemonCloud** [DustinJackson/html-webpack-inline-source-plugin#75]
"webpack": "^4.42",
"html-webpack-plugin": "^4.0.1",

<img width="717" alt="Screen Shot 2020-03-24 at 12 35 50 PM" src="https://user-images.githubusercontent.com/7436361/77388852-3a793780-6dcc-11ea-9c4c-a4c1abfc88a8.png">

**Comment by fmal** [comment]
@DemonCloud @Nemo157 try `npm install html-webpack-inline-source-plugin@beta`

**Comment by fmal** [comment]
@DemonCloud, @Nemo157 you need to install with `npm install html-webpack-inline-source-plugin@beta` and in webpack config pass `webpack-html-plugin` instance: `new HtmlInlineSourcePlugin(HtmlPlugin)`. @DustinJackson would be great to switch from beta release to official now that the `webpack-html-plugin` is at 4.x

**Comment by DemonCloud** [comment]
@fmal  is also not working for me, the beta this 1.0.0.beta2 version

**Comment by jantimon** [comment]
Facebook provides a very nice inline source plugin:

https://github.com/facebook/create-react-app/blob/edc671eeea6b7d26ac3f1eb2050e50f75cf9ad5d/packages/react-dev-utils/InlineChunkHtmlPlugin.js#L10

Maybe we can move the idea into this plugin so there is a stand alone npm package?

Here is the code:

```js
class InlineSourceHtmlPlugin {
  constructor(htmlWebpackPlugin, tests) {
    this.htmlWebpackPlugin = htmlWebpackPlugin;
    this.tests = tests;
  }

  getInlinedTag(publicPath, assets, tag) {
    if (tag.tagName !== 'script' || !(tag.attributes && tag.attributes.src)) {
      return tag;
    }
    const scriptName = publicPath
      ? tag.attributes.src.replace(publicPath, '')
      : tag.attributes.src;
    if (!this.tests.some(test => scriptName.match(test))) {
      return tag;
    }
    const asset = assets[scriptName];
    if (asset == null) {
      return tag;
    }
    return { tagName: 'script', innerHTML: asset.source(), closeTag: true };
  }

  apply(compiler) {
    let publicPath = compiler.options.output.publicPath || '';
    if (publicPath && !publicPath.endsWith('/')) {
      publicPath += '/';
    }

    compiler.hooks.compilation.tap('InlineSourceHtmlPlugin', compilation => {
      const tagFunction = tag =>
        this.getInlinedTag(publicPath, compilation.assets, tag);
      const hooks = this.htmlWebpackPlugin.getHooks(compilation);
      hooks.alterAssetTagGroups.tap('InlineChunkHtmlPlugin', assets => {
        assets.headTags = assets.headTags.map(tagFunction);
        assets.bodyTags = assets.bodyTags.map(tagFunction);
      });
    });
  }
}
```

**Comment by DemonCloud** [comment]
@jantimon get this!

**Comment by d-bitz** [comment]
I'll take a look at update this weekend, PRs are welcome

**Comment by evandiamond** [comment]
Really looking forward to these fixes/additions. Thanks for all your hard work on this plugin @DustinJackson

**Comment by d-bitz** [comment]
I agree with @jantimon, since facebook already has a similar plugin we can move the idea there.  I will deprecate the repository with a link.

**Comment by creage** [comment]
@DustinJackson please don't deprecate this plugin, as having the similar in create-react-app does not solve the issue for people who does not use that library. We need a standalone npm package.

**Comment by evandiamond** [comment]
Agreed. I don’t use react either and could really use this plugin in my
project.

**Comment by creage** [comment]
In order someone is still looking for working package - there is [style-ext-html-webpack-plugin](https://www.npmjs.com/package/style-ext-html-webpack-plugin) which works fine with latest html-webpack-plugin

**Comment by evandiamond** [comment]
@creage Could you show a working example of your config that allows this to work? Appreciate it.

**Comment by yairopro** [comment]
> In order someone is still looking for working package - there is [style-ext-html-webpack-plugin](https://www.npmjs.com/package/style-ext-html-webpack-plugin) which works fine with latest html-webpack-plugin

@creage  your package seems to inject css styles only. What about js ?

@evandiamond Did you find a standalone module for this plugin ?

**Comment by creage** [comment]
@yairopro For JS we use [script-ext-html-webpack-plugin](https://github.com/numical/script-ext-html-webpack-plugin), but it [can't handle multiple HTML entries](https://github.com/numical/script-ext-html-webpack-plugin/issues/43).

**Comment by yairopro** [comment]
Thanks a lot @creage ! 
I will have a look on it.

----

@evandiamond I've found the [npm package](https://www.npmjs.com/package/react-dev-utils) that includes the InlineSourceHtmlPlugin by facebook.
`const InlineChunkHtmlPlugin = require("react-dev-utils/InlineChunkHtmlPlugin");`

**Comment by yairopro** [comment]
@creage THanks again. I finally adopted this plugin 😁.

For people who pass by this issue, here's my config:
```
const HtmlWebpackPlugin = require("html-webpack-plugin");
const ScriptExtHtmlWebpackPlugin = require("script-ext-html-webpack-plugin");
const path = require("path");

module.exports = {
	entry: path.resolve(__dirname, 'src/index.js'),

	output: {
		 // do not set it to "index.html", otherwise your html will be empty
		// filename: "index.html"

		path: path.resolve(__dirname, 'build'),
	},

	plugins: [
		new HtmlWebpackPlugin(),
		new ScriptExtHtmlWebpackPlugin({
			inline: /\.js$/,
		}),
	],
};
```
