### ISSUE TITLE
Could I use template?

### ISSUE THREAD

**Issue by lixinliang** [DustinJackson/html-webpack-inline-source-plugin#8]
When `inject` is true, it works.
```js
new HtmlWebpackPlugin({
    minify : false,
    filename,
    inlineSource : '.(js|css)$',
})
```

I want to use template to control the position of script.
```js
new HtmlWebpackPlugin({
    minify : false,
    inject : false,
    filename,
    template,
    inlineSource : '.(js|css)$',
})
```
And the template like this,
```ejs
<% for (key in htmlWebpackPlugin.files.chunks) { %>
<script src="<%= htmlWebpackPlugin.files.chunks[key].entry %>" type="text/javascript"></script>
<% } %>
```
And which attribute is the source ?

**Comment by d-bitz** [comment]
As you discovered this plugin works by modifying the injected html tag definitions.  From the [documentation](https://github.com/ampedandwired/html-webpack-plugin#writing-your-own-templates) only the files (not source) are available to you as variables.

**Comment by DustinJackson** [comment]
This plugin works by modifying the html tags injected by the html-webpack-plugin.

**Comment by lixinliang** [comment]
Got it.
